const UDP_HOST = '127.0.0.1';
const UDP_PORT = 11255;

const AMQP_HOST = '172.19.0.7';
const AMQP_PORT = 5672;
const AMQP_EXCHANGE = 'jen_ex';
const AMQP_USERNAME = 'nodejs';
const AMQP_PASSWORD = 'pggjLPSPGAWK4ACaJRiX';

module.exports = { UDP_HOST, UDP_PORT, AMQP_HOST, AMQP_PORT, AMQP_EXCHANGE, AMQP_USERNAME, AMQP_PASSWORD };
