
const UDP_HOST = '172.17.0.200';
const UDP_PORT = 11245;
const UDP_PORT2 = 11256;
const AMQP_HOST = '172.19.0.5';
const AMQP_PORT = 5672;
const AMQP_EXCHANGE = 'jen_ex';
const AMQP_USERNAME = 'nodejs';
const AMQP_PASSWORD = 'pggjLPSPGAWK4ACaJRiX';

module.exports = { UDP_HOST, UDP_PORT, UDP_PORT2, AMQP_HOST, AMQP_PORT, AMQP_EXCHANGE, AMQP_USERNAME, AMQP_PASSWORD };
