#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:5.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
WORKDIR /src
#COPY ["nuget.config", "."]
COPY ["src/AGV.Laundry.MqClient/Drop.LocationEngine.MqClient.csproj", "src/AGV.Laundry.MqClient/"]
COPY ["src/AGV.Laundry.HttpApi.Host/Drop.LocationEngine.HttpApi.Host.csproj", "src/AGV.Laundry.HttpApi.Host/"]
COPY ["src/AGV.Laundry.Application/Drop.LocationEngine.Application.csproj", "src/AGV.Laundry.Application/"]
COPY ["src/AGV.Laundry.Application.Contracts/Drop.LocationEngine.Application.Contracts.csproj", "src/AGV.Laundry.Application.Contracts/"]
COPY ["src/AGV.Laundry.Domain.Shared/Drop.LocationEngine.Domain.Shared.csproj", "src/AGV.Laundry.Domain.Shared/"]
COPY ["src/AGV.Laundry.Domain/Drop.LocationEngine.Domain.csproj", "src/AGV.Laundry.Domain/"]
COPY ["src/AGV.Laundry.MongoDB/Drop.LocationEngine.MongoDB.csproj", "src/AGV.Laundry.MongoDB/"]
COPY ["src/AGV.Laundry.HttpApi/Drop.LocationEngine.HttpApi.csproj", "src/AGV.Laundry.HttpApi/"]
RUN dotnet restore "src/AGV.Laundry.MqClient/AGV.Laundry.MqClient.csproj"
COPY . .
WORKDIR "/src/src/AGV.Laundry.MqClient"
RUN mv appsettings.production.json appsettings.json
RUN dotnet build "AGV.Laundry.MqClient.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "AGV.Laundry.MqClient.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "AGV.Laundry.MqClient.dll"]
